import "./globals.css";
import Nav from "./components/Nav/Nav";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeftLong } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

import Footer from "./components/Footer/Footer";

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false; 

export const metadata = {
  title: "Verse-Service Contract",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className="flex pl-10 items-center font-bold">
          <Link
            href="/"
            className="left-icon h-12 w-12 flex items-center justify-center rounded-full text-2xl mr-4"
          >
            <FontAwesomeIcon className="p-3.5" icon={faArrowLeftLong} />
          </Link>
          <h3 className="gradient-text">Service Contract</h3>
          <span className="span w-4/5 h-[1px] ml-2.5"></span>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
